functions1 = ['tail_bytes', 'pretty_name', 'cl_strtod', 'quotearg_style', 'close_stdout', 'writers_are_dead', 'tail', 'check_nonnull', 'xstrtoumax', 'rpl_fclose', 'set_program_name', 'record_open_fd', 'tailable_stdin', 'argmatch', 'valid_file_spec', 'is_local_fs_type', 'fremote', 'any_remote_file', 'write_header', 'file_lines', 'c_tolower', 'xpalloc', 'xreallocarray', 'tail_file', 'fd_safer', '__gl_setmode', 'open_safer', 'tail_lines', 'pipe_lines', 'close_fd', 'parse_options', 'quotearg_n_style_colon', 'xlseek', 'tail_forever', 'xstrtod', 'quotearg_n_options', 'quoting_options_from_style', 'xmalloc', 'dtotimespec', 'version_etc', 'safe_read', 'version_etc_va', 'parse_obsolete_option', 'set_binary_mode', 'any_non_remote_file', 'set_char_quoting', 'any_live_files', 'version_etc_arn', 'c_strcasecmp', 'check_output_alive', 'rpl_fflush', 'posix2_version', 'xnumtoumax', 'quotearg_n_style', 'xwrite_stdout', 'rpl_nanosleep', 'xnanosleep', 'locale_charset', 'ignore_fifo_and_pipe', 'get_stat_mtime', 'xdectoumax', 'dump_remainder', 'xrealloc', 'recheck', '__xargmatch_internal', 'proper_name_lite', 'main_0', 'rpl_fcntl', 'close_stream', 'pipe_bytes', 'xnmalloc', 'quotearg_buffer_restyled']
functions2 = ["set_program_name", "posix2_version", "bkm_scale", "bkm_scale_by_power", "xstrtoumax", "xalloc_die", "xrealloc", "xpalloc", "locale_charset", "c_tolower", "c_strcasecmp", "gettext_quote", "mbszero", "setlocale_null_unlocked", "setlocale_null_r_unlocked", "setlocale_null_r", "hard_locale", "rpl_mbrtoc32", "c32isprint", "quotearg_buffer_restyled", "check_nonnull", "xmalloc", "xcharalloc", "quotearg_n_options", "quote_n_mem", "quote_n", "quote", "parse_obsolete_option", "xnumtoumax", "xdectoumax", "argmatch", "argmatch_exact", "quoting_options_from_style", "quotearg_n_style", "argmatch_invalid", "argmatch_valid", "__xargmatch_internal", "xstrtod", "emit_stdin_note", "emit_mandatory_arg_note", "emit_ancillary_info", "usage", "proper_name_lite", "version_etc_arn", "version_etc_va", "version_etc", "parse_options", "quotearg_style", "xreallocarray", "xnmalloc", "xset_binary_mode", "rpl_fcntl_DUPFD", "rpl_fcntl_DUPFD_CLOEXEC", "rpl_fcntl", "dup_safer", "fd_safer", "open_safer", "pretty_name", "write_header", "safe_read", "xwrite_stdout", "start_lines", "dump_remainder", "offtostr", "set_char_quoting", "quotearg_n_style_colon", "xlseek", "file_lines", "pipe_lines", "tail_lines", "start_bytes", "usable_st_size", "pipe_bytes", "tail_bytes", "tail", "close_fd", "get_stat_mtime", "record_open_fd", "is_local_fs_type", "fremote", "tail_file", "ignore_fifo_and_pipe", "tailable_stdin", "any_remote_file", "any_non_remote_file", "any_symlinks", "any_non_regular_fifo", "write_error", "check_tuning", "is_prime", "next_prime", "compute_bucket_size", "hash_initialize", "last_component", "dir_len", "safe_hasher", "free_entry", "hash_find_entry", "allocate_entry", "transfer_entries", "hash_rehash", "hash_insert_if_absent", "hash_insert", "valid_file_spec", "recheck", "timespec_cmp", "check_fspec", "hash_get_n_entries", "writers_are_dead", "die_pipe", "hash_remove", "hash_lookup", "tail_forever_inotify", "hash_free", "any_live_files", "iopoll_internal", "iopoll", "check_output_alive", "make_timespec", "dtotimespec", "rpl_nanosleep", "xnanosleep", "tail_forever", "main_0"]


only_in_1 = set(functions1) - set(functions2)
only_in_2 = set(functions2) - set(functions1)


print(only_in_1)
print(only_in_2)