import subprocess
import random

# This script runs the `zopfli-test` executable, with an STDIN buffer of randomly generated bytes

def generate_random_bytes(size):
    """Generate a string of random bytes of the specified size."""
    return bytes(random.getrandbits(8) for _ in range(size))

def run_zopfli_test():
    """Run the zopfli test with random input."""
    # Generate a random byte string of size 3000
    random_bytes = generate_random_bytes(3000)
    
    # Run the zopfli test executable with the random bytes as input
    process = subprocess.Popen(
        ['zopfli-test'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    
    _, stderr = process.communicate(input=random_bytes)
    
    if process.returncode != 0:
        print("Error running zopfli-test:", stderr.decode())
        exit(1)
    else:
        print("Tests passed")

if __name__ == "__main__":
    run_zopfli_test()